language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install coverage       # Add me to install coverage.py
script:
  coverage user_stories.py run run.py -t
after_success:
  - coveralls
