language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install coverage       # Add me to install coverage.py
script:
  coverage run --source=run.py --test
after_success:
  - coveralls
